# Generated by Django 4.0.3 on 2022-04-03 02:23

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_statfactory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='statstore',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.machine'),
        ),
        migrations.AddField(
            model_name='statstore',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.storeproduct'),
        ),
        migrations.AddField(
            model_name='storecategories',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.machine'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
