# Generated by Django 4.0.3 on 2022-04-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_statstore_machine_statstore_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statfactory',
            old_name='count',
            new_name='product_count',
        ),
    ]
