# Generated by Django 4.0.3 on 2022-04-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_count_statfactory_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statfactory',
            old_name='product_count',
            new_name='count',
        ),
    ]
