# Generated by Django 4.0.3 on 2022-04-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_rename_product_count_statfactory_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statstore',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='storecategories',
            name='machine',
        ),
    ]
