# Generated by Django 4.0.3 on 2022-04-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_statstore_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
